### ISSUE TITLE
How to prevent keys from being symbolized when parsing JSON

### ISSUE THREAD

**Issue by picatz** [socketry/async-rest#1]
👋 Hello @ioquatix! 

I'm looking to use `async-rest` in `shodanz`: https://github.com/picatz/shodanz/pull/18

But, I ran into a problem with the [default behavior of symbolized keys when parsing the JSON](https://github.com/socketry/async-rest/blob/master/lib/async/rest/wrapper/json.rb#L72).

While I believe symbolizing keys is probably the right default, I'm honestly struggling with correcting that behavior without [monkey-patching](https://github.com/picatz/shodanz/blob/async-rest/lib/shodanz/apis/utils.rb#L12) `async-rest`, which I don't believe is the *correct* solution to my problem.

:bow: Can you please advise on how to handle this situation?

**Comment by ioquatix** [comment]
Because there are almost always going to be different requirements on formats, the JSON one is only included as a canonical example.

You should make your own subclass of `Wrapper::JSON`. We could probably make your use case a bit simpler, thought, by exposing some options for parsing.

Here is an example of interfacing with a very weird API that wraps JSON into the URL encoded post.

```ruby
class ScriptWrapper < Async::REST::Wrapper::URLEncoded
	def process_response(request, response)
		if content_type = response.headers['content-type']
			if content_type.start_with? Async::REST::Wrapper::JSON::APPLICATION_JSON
				if body = response.body
					response.body = Async::REST::Wrapper::JSON::Parser.new(body)
				end
			else
				warn "Unknown content type: #{content_type}!"
			end
		end
		
		return response
	end
end

url = "https://system/script.php"
poll = Async::REST::Resource.for(url, {
	'user-agent' => 'foobar'
})

Async.logger.debug!

Async do
	begin
		representation = Async::REST::Representation.new(poll, wrapper: ScriptWrapper.new)
		
		response = representation.post(jsondata: JSON.dump(payload))
		
		pp response.read
	ensure
		representation&.close if representation
	end
end
```

**Comment by ioquatix** [comment]
Another thing to be aware of is that the body wrapper is actually wrapping around the streaming response body - so if you have a large response you might like to do it in a way which parses JSON incrementally. I've been working on a newline separated JSON wrapper too.

**Comment by ioquatix** [comment]
Here is some more code:

https://github.com/socketry/cloudflare/blob/master/lib/cloudflare/representation.rb

We separate out handling of the message format and errors from the actual protocol itself, that way it gets reused everywhere.

Let me show you how to do it.

**Comment by ioquatix** [comment]
I don't know if this works or not but maybe something like:

```ruby
class Shodanz::REST::Wrapper < Async::REST::Wrapper::JSON
	class Parser < HTTP::Body::Wrapper
		RATELIMIT = 'rate limit reached'
		NOINFO = 'no information available'
		NOQUERY = 'empty search query'
		
		def handle_any_json_errors(json)
			return json unless json.is_a?(Hash) && json.key?('error')
			
			raise Shodanz::Errors::RateLimited if json['error'].casecmp(RATELIMIT) >= 0
			raise Shodanz::Errors::NoInformation if json['error'].casecmp(NOINFO) >= 0
			raise Shodanz::Errors::NoQuery if json['error'].casecmp(NOQUERY) >= 0
			
			json
		end
		
		def join
			handle_any_json_errors(
				::JSON.parse(super, symbolize_names: false)
			)
		end
	end
end
```

**Comment by picatz** [comment]
I'm genuinely struggling to understand exactly how to make my own wrapper, even with the given example. I've gone through a few tries to implement this so far, but end up getting lost.

I have a vague understanding, but not enough to pull all the pieces together quite yet. 🤦‍♂

**Comment by picatz** [comment]
Persistence prevails! I'm able to use a representation and a custom-ish wrapper to get the job done.

Still need to wrap my head around some of it though.

**Comment by ioquatix** [comment]
I based the implementation on the REST thesis. It might help to read it. But the gist of it is you have resources which when you get them, give you a representation of the resource. The idea is to decouple the model from the format of the response. The thesis has more details.

**Comment by picatz** [comment]
🙏Thank you for your help.
