### ISSUE TITLE
Examples are no longer correct after recent API changes

### ISSUE THREAD

**Issue by uberjay** [socketry/async-rest#12]
Unfortunately, while the API may be simplified, the getting started guide is pretty terse and the examples haven't been updated.

I *think* I figured out how to map my existing code to the new API, but I'm not totally sure, which makes me nervous! 😅

**Comment by ioquatix** [comment]
Do you want to share the changes you had to make and I'll confirm it.

Sorry about the changes.

**Comment by ioquatix** [comment]
Let me apologise again for the changes.

I'm extremely happy with the changes, and I've started using this gem more.

I've added more examples so you can see examples of how I expect the library to be used:

https://github.com/socketry/async-rest?tab=readme-ov-file#see-also

If you have an open source project and you want help migrating / updating it, please do let me know.
